# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ape_pat', models.CharField(max_length=50)),
                ('ape_mat', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_edicion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
                ('vigente', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('longitud', models.FloatField()),
                ('pob_inicial', models.IntegerField()),
                ('pob_final', models.IntegerField()),
                ('pto_partida', models.CharField(max_length=200)),
                ('pto_llegada', models.CharField(max_length=200)),
                ('id_edicion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Edicion')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insc', models.DateTimeField(auto_now=True)),
                ('id_ciclista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Ciclista')),
                ('id_edicion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Edicion')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_serie', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='edicion',
            name='id_serie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Serie'),
        ),
    ]
